### ISSUE TITLE
Load 2 batches at once

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_dataloader#109]
## Detailed Description
Would it be worth loading 2 batches at once and taking and randon (seeded) sample of examples from each one. 
This would mean the that the ML models dont see the same batch each epoch. This might help stop over fitting.

**Comment by jacobbieker** [comment]
Yeah! I think shuffling up the examples a bit more would probably be good.

**Comment by JackKelly** [comment]
yup, SGTM!
