### ISSUE TITLE
Failing test: `tests/test_position_encoding.py::test_batch_encoding`

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataloader#127]
**Describe the bug**
`tests/test_position_encoding.py::test_batch_encoding` fails at line 53 because `torch.max(position_encodings[position_encoding_key])` is too large. It's expected to be less than or equal to 1. But it's actually 1.3904!

![image](https://user-images.githubusercontent.com/460756/176457625-439fa98f-9930-4291-900c-d11ad9c02b0f.png)

@jacobbieker if you can give me a hint, I'm happy to try to debug. Unless you're happy to do it? :slightly_smiling_face: 

**To Reproduce**
`py.test tests/test_position_encoding.py::test_batch_encoding`

**Comment by jacobbieker** [comment]
I'd almost just remove that functionality? We aren't using it, and its not particularly fast. But happy to dive in a debug otherwise!

**Comment by JackKelly** [comment]
OK! Would you be happy to rip out the unused functionality? I definitely like the approach of removing unused stuff :slightly_smiling_face:

**Comment by jacobbieker** [comment]
Position encoding and SatFlow datamodules have been removed now, so it should be quite a bit smaller!

**Comment by JackKelly** [comment]
Awesome, thanks!
