### ISSUE TITLE
Generate test data on the fly

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/nowcasting_dataloader#37]
## Detailed Description
Run the test generation script in the test action. 

## Context
This would fix stale test data from causing problems and making tests pass that shouldn't. 

## Possible Implementation
Add a step in the tests that calls the test generation script, either in the reusable workflow or here

**Comment by peterdudfield** [comment]
You can use the FakeDataset for this. 
https://github.com/openclimatefix/nowcasting_dataloader/blob/main/nowcasting_dataloader/fake.py

**Comment by jacobbieker** [comment]
Yeah, that can work, but I was more thinking for the ones that test loading from the NetCDF files, to instead make those NetCDF files on the fly and then loading them for the tests that use that, the `test_netcdf_dataset` and such

**Comment by peterdudfield** [comment]
So a test could be 
1. create netcdf in temp folder
2. run dataset loader using the temp folder
