### ISSUE TITLE
Multi-scale position encoding

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataloader#38]
## Detailed Description
Should we implement "multi-scale" position encoding?  e.g., for temporal encoding, we could have a total of 8 channels:

A full cycle of a sine and cosine for:
* day-of-year
* time-of-day
* 6-hours
* 2-hours

The thinking being that, if we only have day-of-year and time-of-day, then it might be hard for the model to tell if two timesteps are consecutive (because 5 minutes would be represented as a tiny change in a sine wave which takes a full 24 hours to complete)

(Also, if we get into electricity demand forecasting, we'd want "human" temporal encoding like day-of-week)

**Comment by JackKelly** [comment]
This implemented now, I think.  Is that right, @jacobbieker?

**Comment by jacobbieker** [comment]
Yeah, as in it gives multiple Fourier features per 'scale' of time, but not specifically for 6 hours or 2 hours ones

**Comment by JackKelly** [comment]
cool, yeah, that's perfect :slightly_smiling_face:   I'll close this issue
