### ISSUE TITLE
Add PV/Unified Position encoding

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/nowcasting_dataloader#4]
## Detailed Description
As mentioned in https://github.com/openclimatefix/satflow/issues/101 it would be helpful to have a way of having consistent position encodings for the PV systems/satellite imagery so that the model can associate the PV systems output in time and space with the satellite imagery. 

This unified position encoding could also be useful for other modalities, so that the model only needs one set of position encodings but can use it for all the input modalities.

## Context
It would help with the joint model and unifying the inputs/outputs. This position encoding can also be used with the https://github.com/openclimatefix/perceiver-pytorch/issues/20 to ensure the queries use the same positional encodings when getting the output

## Possible Implementation
Could be just a way of encoding all of this with Fourier Features. Or could be some other way of encoding that works across the different modalities

**Comment by JackKelly** [comment]
> get the maximum spatial and temporal extant of all the input modalities, create an encoding based off that, and then 'slice' it up for each of the individual modalities

SGTM!  Thank you!
