### ISSUE TITLE
Satellite and nwp channel strings --> torch

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_dataloader#46]
**Describe the bug**
array of strings for channel names can not be converted to torch

```
    return torch.tensor(self._obj.data, dtype=torch.float32)
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

```

**To Reproduce**
run the most recenet dataset
'/mnt/storage_b/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/prepared_ML_training_data/v10'
and it errors when trying to turn array of strings to a torch filed

**Expected behavior**
dataset can be turned into torch tensors

**Possibile soultions**
- Convert strings to numbers by using channels as index

**Comment by peterdudfield** [comment]
Could I get your advice on this @jacobbieker , happy for the channels strings to be changed to an index of numbers?

**Comment by jacobbieker** [comment]
What array of strings is it? The issue I see with changing strings ti numbers using the channel name is that if we change what channels we use, it could mess that up easily, incase we don't use all 12 channels

**Comment by peterdudfield** [comment]
yea so i was thinking of using a mapping from 'channel_name' to an index?

**Comment by JackKelly** [comment]
Will we ever need to give the channel names to Torch? Is it sufficient to identify the channels by the ordering of the channel dimension?

**Comment by peterdudfield** [comment]
We probably want to make sure that 
- ['name_1', 'name_2'] 
-  ['name_1', 'name_3'] 
are represented differently, 

but other that that i think its ok

**Comment by jacobbieker** [comment]
Yeah, I guess it wouldn't be important for giving Torch the names, I was more going for us to know what is happening, but I guess thats saved in the config anyway!

**Comment by JackKelly** [comment]
Is the main use case to tell the "modality encoding" code which channel is which? In which case, is that encoding done before pytorch?

**Comment by jacobbieker** [comment]
That isn't encoded at all right now actually, its only encoded in time and space, not channels

**Comment by peterdudfield** [comment]
https://github.com/openclimatefix/nowcasting_dataloader/pull/48
This is what I was thinking

1. Dataset should save the channgel names in the xr.dataset as it useful to see. Although it is also in the config, so we could remove it
2. converting Dataset to torch, need to change it to indexes (away from strings)

**Comment by JackKelly** [comment]
1 sounds great, thank you!

2 before bothering to convert names to Torch, please can we figure out what the use case is? :)

**Comment by jacobbieker** [comment]
> That isn't encoded at all right now actually, its only encoded in time and space, not channels

Although, now that we are using native resolution images, I guess there will be two modalities, one for HRV and one for the rest of the channels

**Comment by peterdudfield** [comment]
> 1 sounds great, thank you!
> 
> 2 before bothering to convert names to Torch, please can we figure out what the use case is? :)

2. so perhaps for the moment, we just dont pass the channels names to Torch, and if we come up with a use case we can add it?

**Comment by JackKelly** [comment]
Awesome, SGTM! Thank you!
