### ISSUE TITLE
Recompute Mean/Std for Satellite data

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/nowcasting_dataloader#53]
## Detailed Description
Now that we are using the original projection of the satellite data, the mean and std are probably close, but still wrong for the new format. So we need to rerun the calculation for all the channels.

## Context
We need it to have the correct normalization.

**Comment by JackKelly** [comment]
You probably know this already but, in _principle_, now that the satellite data is in Zarr, it _should_ be possible to use Dask to compute the means and standard deviations across the entire Zarr dataset (and Dask will handle loading the data in chunks so as not to swamp the main memory).  But, in practice, I still find that dask doesn't always work perfectly out-of-the-box!
