### ISSUE TITLE
Check our models are getting this configuration of data inputs

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataloader#59]
## General
- [ ] The target should be future GSP power and, optionally, future satellite imagery 

## The model should receive these as inputs
- [ ] An embedding of the GSP ID (also see https://github.com/openclimatefix/nowcasting_dataset/issues/451)
- [ ] Historical data from all individual PV systems within the region of interest (which almost certainly will be available at inference time and is probably important so the model can see how much sunlight each cloud is letting through!), probably including:
    - [ ] An embedding of each PV system's ID (so the model can learn which PV systems to trust)?
    - [ ] The spatial and temporal location of each PV reading

## The model should NOT receive these as inputs :slightly_smiling_face:
- [ ] Triple-check that we're not accidentally giving the model future GSP power as an input :slightly_smiling_face:  (mistakes like this are all too easy to make!)
- [ ] Historical GSP power data (because that won't be available at inference time!)
- [ ] Future satellite images :slightly_smiling_face: 
- [ ] Future data from individual PV systems

**Comment by jacobbieker** [comment]
The target should probably also optionally be the future satellite imagery too?

**Comment by JackKelly** [comment]
Ah, yes, good point! I'll add that to the list

**Comment by peterdudfield** [comment]
Also, we should give future PV values too?

**Comment by jacobbieker** [comment]
Okay, I started a new dataset based off one I had for SatFlow that should ensure all these things in #60

**Comment by JackKelly** [comment]
> we shouldnt give future PV values too?

Good point!  I've added that to the list, too!
